steps:
- task: Gradle@2
  displayName: "Gradle: Build"

  inputs:
    options: "-PtestForks=4"
    gradleOptions: "-Xmx2048m"

    javaHomeOption: "JDKVersion"
    jdkVersionOption: "$(jdk_version)"
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: '$(System.DefaultWorkingDirectory)build/test-results/test/**/TEST-*.xml'

